### ISSUE TITLE
Vivliostyle.js issues

### ISSUE THREAD

**Issue by MurakamiShinyu** [baldurbjarnason/vivliostyle-tests#1]
@baldurbjarnason Thanks for the bug reports! I confirmed the bugs. See below:

## Contents, Cover, and custompage2

Thanks, I opened Vivliostyle.js issue:
- [Named page at the first page is not applied when HTML head part is big (vivliostyle/vivliostyle.js#770)](https://github.com/vivliostyle/vivliostyle.js/issues/770)

## custompage

I opened Vivliostyle.js issue:
- [Named page not properly changed when target-counter refers the page (vivliostyle/vivliostyle.js#771)](https://github.com/vivliostyle/vivliostyle.js/issues/771)

## Not Selector

I opened Vivliostyle.js issue:
- [The :not() selector not working when the argument is an ID selector (vivliostyle/vivliostyle.js#769)](https://github.com/vivliostyle/vivliostyle.js/issues/769)

## Italics

This is a known issue of Vivliostyle.js:
- [Root element styles are not inherited to page context (vivliostyle/vivliostyle.js#568)](https://github.com/vivliostyle/vivliostyle.js/issues/568)

Until this bug is fixed, the same style as the root element needs to be specified in `@page {…}`, e.g.,

```css
      html {
        font-family: Literata, "Iowan Old Style", "Sitka Text", Palatino,
          "Book Antiqua", serif;
      }
      @page {
        font-family: Literata, "Iowan Old Style", "Sitka Text", Palatino,
          "Book Antiqua", serif;
      }
```
